### ISSUE TITLE
500 Internal Server Error after update  9.1 to 9.2

### ISSUE THREAD

**Issue by mikweb2017** [WWBN/AVideo#3458] opened 2020-08-02 16:00 UTC
**Describe the bug**
500 Internal Server Error after update  9.1 to 9.2 update git pull

**To Reproduce**
https://you-tube.eu/

PHP 7.4

ubuntu 16.04

LOGS
[Sun Aug 02 17:53:08.102351 2020] [proxy_fcgi:error] [pid 5580] [client 46.229.168.161:2158] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:53:08.102451 2020] [proxy_fcgi:error] [pid 5580] [client 46.229.168.161:2158] AH01070: Error parsing script headers
[Sun Aug 02 17:53:08.102458 2020] [proxy_fcgi:error] [pid 5580] (22)Invalid argument: [client 46.229.168.161:2158] AH01075: Error dispatching request to : 
[Sun Aug 02 17:53:14.918648 2020] [proxy_fcgi:error] [pid 9018] [client 91.64.181.76:62457] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:53:14.918763 2020] [proxy_fcgi:error] [pid 9018] [client 91.64.181.76:62457] AH01070: Error parsing script headers
[Sun Aug 02 17:53:14.918771 2020] [proxy_fcgi:error] [pid 9018] (22)Invalid argument: [client 91.64.181.76:62457] AH01075: Error dispatching request to : 
[Sun Aug 02 17:54:00.637501 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.151:9986] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:54:00.637604 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.151:9986] AH01070: Error parsing script headers
[Sun Aug 02 17:54:00.637611 2020] [proxy_fcgi:error] [pid 5221] (22)Invalid argument: [client 46.229.168.151:9986] AH01075: Error dispatching request to : 
[Sun Aug 02 17:54:12.743102 2020] [proxy_fcgi:error] [pid 5232] [client 114.119.160.43:57384] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:54:12.743306 2020] [proxy_fcgi:error] [pid 5232] [client 114.119.160.43:57384] AH01070: Error parsing script headers
[Sun Aug 02 17:54:12.743326 2020] [proxy_fcgi:error] [pid 5232] (22)Invalid argument: [client 114.119.160.43:57384] AH01075: Error dispatching request to : 
[Sun Aug 02 17:54:49.161630 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.139:29100] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:54:49.161750 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.139:29100] AH01070: Error parsing script headers
[Sun Aug 02 17:54:49.161759 2020] [proxy_fcgi:error] [pid 5221] (22)Invalid argument: [client 46.229.168.139:29100] AH01075: Error dispatching request to : 
[Sun Aug 02 17:54:51.919567 2020] [proxy_fcgi:error] [pid 9043] [client 46.229.168.136:38388] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:54:51.919674 2020] [proxy_fcgi:error] [pid 9043] [client 46.229.168.136:38388] AH01070: Error parsing script headers
[Sun Aug 02 17:54:51.919682 2020] [proxy_fcgi:error] [pid 9043] (22)Invalid argument: [client 46.229.168.136:38388] AH01075: Error dispatching request to : 
[Sun Aug 02 17:55:06.147398 2020] [proxy_fcgi:error] [pid 9045] [client 46.229.168.154:57100] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:55:06.147520 2020] [proxy_fcgi:error] [pid 9045] [client 46.229.168.154:57100] AH01070: Error parsing script headers
[Sun Aug 02 17:55:06.147528 2020] [proxy_fcgi:error] [pid 9045] (22)Invalid argument: [client 46.229.168.154:57100] AH01075: Error dispatching request to : 
[Sun Aug 02 17:55:12.227454 2020] [proxy_fcgi:error] [pid 6085] [client 46.229.168.141:41364] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:55:12.227561 2020] [proxy_fcgi:error] [pid 6085] [client 46.229.168.141:41364] AH01070: Error parsing script headers
[Sun Aug 02 17:55:12.227569 2020] [proxy_fcgi:error] [pid 6085] (22)Invalid argument: [client 46.229.168.141:41364] AH01075: Error dispatching request to : 
[Sun Aug 02 17:55:18.158368 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.152:12770] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:55:18.158569 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.152:12770] AH01070: Error parsing script headers
[Sun Aug 02 17:55:18.158589 2020] [proxy_fcgi:error] [pid 5221] (22)Invalid argument: [client 46.229.168.152:12770] AH01075: Error dispatching request to : 
[Sun Aug 02 17:56:18.142103 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.136:51010] malformed header from script 'index.php': Bad header: 
[Sun Aug 02 17:56:18.142210 2020] [proxy_fcgi:error] [pid 5221] [client 46.229.168.136:51010] AH01070: Error parsing script headers
[Sun Aug 02 17:56:18.142217 2020] [proxy_fcgi:error] [pid 5221] (22)Invalid argument: [client 46.229.168.136:51010] AH01075: Error dispatching request to : 
AVideo logs
2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 17:59:55 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 17:59:55 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 17:59:55 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 16:00:03 UTC] AVideoLog::DEBUG: IP2Location::getLocation(46.229.168.141) [Bot] SEMRush {"ip_from":786802688,"ip_to":786802943,"country_code":"NL","country_name":"Netherlands","region_name":"Noord-Holland","city_name":"Amsterdam","ip":"46.229.168.141"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 18:00:04 Europe/Berlin] AVideoLog::DEBUG: IP2Location::getLocation(127.0.0.1) Unknow {"ip_from":2130706432,"ip_to":2147483647,"country_code":"-","country_name":"-","region_name":"-","city_name":"-","ip":"127.0.0.1"}
[02-Aug-2020 16:00:05 UTC] AVideoLog::WARNING: Warning: The plugin [Cache::getEnd] takes 0.5171 seconds to complete. 
[02-Aug-2020 16:00:05 UTC] AVideoLog::WARNING: /var/www/vhosts/you-tube.eu/httpdocs/YouPHPTube/view/index.php

**Comment by jyrihovila** [comment] 2020-08-02 16:52
This is a know issue with version 9.2 vs PHP-FPM. A quick "fix" is to switch to using mod_php instead of PHP-FPM.

@DanielnetoDotCom needs more detailed debug information in order to fix the issue.

My report of the same issue: https://github.com/WWBN/AVideo/issues/3428

**Comment by mikweb2017** [comment] 2020-08-02 17:14
@jyrihovila 
can you explain again you fix?

**Comment by jyrihovila** [comment] 2020-08-02 18:18
> @jyrihovila
> can you explain again you fix?

You are using php-fpm, right? I mean you have a separate php-fpm daemon running on your server. The quick-and-ugly "fix" is not to use php-fpm, but instead the Apache's built-in mod_php.

I wish I had the time to explain this in more detail, but I don't, so I will have to resort to giving you these links:

https://www.cloudways.com/blog/php-fpm-on-cloud/#:~:text=Unlike%20PHP%2DFPM%2C%20mod_PHP%20locks,FPM%20is%20the%20way%20forward.

https://medium.com/@jacksonpauls/moving-from-mod-php-to-php-fpm-914125a7f336

It's really not a solution at all to move from php-fpm to mod_php, but currently, it's the only way to get around the HTTP 500 error you described above. PHP-FPM is _much_ more efficient than mod_php, but until @DanielnetoDotCom figures out why 9.2 and PHP-FPM don't work together, all we can do is either 1) use mod_php instead of PHP-FPM or 2) stick / downgrade to version 9.1 of YouPHPTube / AVideo until the issue is solved.

**Comment by jyrihovila** [comment] 2020-08-04 12:38
This issue is fixed by the latest updates made to the code. @mikweb2017 please update to the latest version and let us know if it solves the problem for you.

**Closed** 2020-09-06 13:19 UTC
Labels: bug, wontfix
