### ISSUE TITLE
Thumbnail generated on embed youtube videos is of very poor quality. 

### ISSUE THREAD

**Issue by sarabhi92git** [WWBN/AVideo#2866] opened 2020-04-13 06:44 UTC
Thumbnail generated on embed youtube videos is of very poor quality.
So, I want to use main image as thumbnail.
Please help me @DanielnetoDotCom @hersche @alexious where I can change in code to use poster image as thumbnail.

**Comment by DanielnetoDotCom** [comment] 2020-04-13 13:23
Duplicate of #2865

**Closed by DanielnetoDotCom** 2020-04-13 13:23 UTC
Labels: question
