### ISSUE TITLE
Article plugin

### ISSUE THREAD

**Issue by Andiweb87** [WWBN/AVideo#1990] opened 2019-08-24 21:51 UTC
Nice the article plugin added by you Daniel but need to fix some more to show the article in center view

https://demo.youphptube.com/video/first-thing

**Comment by DanielnetoDotCom** [comment] 2019-08-24 22:52
Hi, I could not see any problem, can you please screenshot?

**Comment by Andiweb87** [comment] 2019-08-25 09:04
![demo11](https://user-images.githubusercontent.com/32053243/63647894-10717100-c728-11e9-9e23-5a1a8c196d12.jpg)

**Comment by Andiweb87** [comment] 2019-08-25 09:14
also is better to show the articles in the main page of gallery in another section different from the last video added section

**Comment by DanielnetoDotCom** [comment] 2019-08-25 11:25
I see you are using theater mode, I had not tested it, I will test and fix in the future

![image](https://user-images.githubusercontent.com/18009293/63649258-cc737180-c711-11e9-9a6a-38420d093f94.png)

**Comment by Andiweb87** [comment] 2019-08-25 11:40
is the demo site in the screenshot i have send to you not my site (same issue also there) , i see the site like you have set the settings in demo, its strange how you see correct the article ...

**Comment by maxlinux2000** [comment] 2019-09-24 05:35
UP!!
the images in the tab Images of Article was not displayed and then the thumbnails was not show in the home page or in Video section.

![Captura de pantalla de 2019-09-24 07-33-12](https://user-images.githubusercontent.com/5683921/65483796-c7831880-de9d-11e9-8298-0b85a1529e4f.png)
![Captura de pantalla de 2019-09-24 07-33-30](https://user-images.githubusercontent.com/5683921/65483797-c7831880-de9d-11e9-93b0-edc8ebad79f2.png)
![Captura de pantalla de 2019-09-24 07-34-11](https://user-images.githubusercontent.com/5683921/65483798-c81baf00-de9d-11e9-8c45-9036d94b6e62.png)

**Comment by DanielnetoDotCom** [comment] 2019-09-24 12:49
Sorry @maxlinux2000 , I dont understand what is the problem?

**Comment by maxlinux2000** [comment] 2019-09-24 15:08
the problem is that I have added a picture of a rainbow and I can't see it anywhere.
I only see the document icon as MS-Word and this is not enough.
If I upload a photo, it has to appear in the thumbnail as in the videos.

**Comment by DanielnetoDotCom** [comment] 2019-09-24 16:14
I just test and it is working in my side

maybe your image upload fail

**Comment by maxlinux2000** [comment] 2019-09-24 16:26
What are the requirements for the images? dimensions ... formats ...

Can you put a link to a photo that works please?

**Comment by DanielnetoDotCom** [comment] 2019-09-24 16:40
any size may work, check your log file for upload errors

**Comment by maxlinux2000** [comment] 2019-09-28 20:31
today I come bak to test the article plugin...

Still not works, Please have a look to the screenshot


![Captura de pantalla de 2019-09-28 21-39-21](https://user-images.githubusercontent.com/5683921/65821700-76767a00-e239-11e9-81c1-ebb231ede3d2.png)

As you can see there is an error in the upload, but I can't see it in the youphptube.logs...

```
root@iesus:/var/www/html# find . -name *.log
./YouPHPTube-Encoder/videos/youphptube.log
./YouPHPTube/videos/youphptube.js.log
./YouPHPTube/videos/youphptube.log
root@iesus:/var/www/html# 

```
 ...or I have to see other logs ?

Here you can download the image I have used
https://www.sbb.ch/en/leisure-holidays/ideas/offer.html/zuege/gotthard-panorama-express17

Here you can see the video 

https://iesus.win/video/youphptube-error2

**Comment by DanielnetoDotCom** [comment] 2019-09-30 11:24
can you please inspect the code and grab the upload response?

![image](https://user-images.githubusercontent.com/18009293/65874231-a9b12a00-e35b-11e9-9531-47c6b33b393b.png)

**Comment by maxlinux2000** [comment] 2019-09-30 19:44
Here you have the pic

![Captura de pantalla de 2019-09-30 21-41-14](https://user-images.githubusercontent.com/5683921/65910646-6c848080-e3cb-11e9-8ea3-d7dcf0e2c7d0.png)

**Comment by maxlinux2000** [comment] 2019-09-30 19:49
just in case
```
4.0K drwxr-xr-x 14 www-data www-data 4.0K Sep 21 19:24 .
4.0K drwxr-xr-x  4 root     root     4.0K Sep 21 19:09 ..
4.0K drwxr-xr-x  8 www-data www-data 4.0K Sep 21 19:09 .git
4.0K drwxr-xr-x  2 www-data www-data 4.0K Sep 21 19:09 .github
4.0K -rw-r--r--  1 www-data www-data 1.4K Sep 21 19:09 .gitignore
 16K -rw-r--r--  1 www-data www-data  13K Sep 21 19:09 .htaccess
4.0K -rw-r--r--  1 www-data www-data   18 Sep 21 19:09 CNAME
4.0K -rw-r--r--  1 www-data www-data 1.5K Sep 21 19:09 Dockerfile
4.0K -rw-r--r--  1 www-data www-data 1.2K Sep 21 19:09 LICENSE
8.0K -rw-r--r--  1 www-data www-data 7.9K Sep 21 19:09 README.md
4.0K drwxr-xr-x  3 www-data www-data 4.0K Sep 21 19:09 admin
 12K -rw-r--r--  1 www-data www-data  11K Sep 21 19:09 classic.htaccess
4.0K drwxr-xr-x  2 www-data www-data 4.0K Sep 21 19:09 docker
4.0K drwxr-xr-x  2 www-data www-data 4.0K Sep 21 19:09 feed
4.0K drwxr-xr-x  9 www-data www-data 4.0K Sep 21 19:09 google
8.0K -rw-r--r--  1 www-data www-data 4.9K Sep 21 19:09 index.php
4.0K drwxr-xr-x  2 www-data www-data 4.0K Sep 21 19:09 locale
4.0K -rw-r--r--  1 www-data www-data 2.0K Sep 21 19:09 new.htaccess
4.0K drwxr-xr-x  7 www-data www-data 4.0K Sep 21 19:09 objects
4.0K drwxr-xr-x 55 www-data www-data 4.0K Sep 21 19:09 plugin
4.0K -rw-r--r--  1 www-data www-data  231 Sep 21 19:09 robots.txt
 16K -rw-r--r--  1 www-data www-data  13K Sep 21 19:09 routes.php
 96K -rw-r--r--  1 www-data www-data  95K Sep 27 23:44 sitemap.xml
4.0K -rw-r--r--  1 www-data www-data  202 Sep 21 19:09 test.txt
4.0K drwxr-xr-x  2 www-data www-data 4.0K Sep 21 19:09 updatedb
180K drwxr-xr-x  4 www-data www-data 176K Sep 30 19:54 videos
4.0K drwxr-xr-x  9 www-data www-data 4.0K Sep 21 19:09 view
4.0K -rw-r--r--  1 www-data www-data  911 Sep 21 19:09 web.config
4.0K -rw-r--r--  1 www-data www-data 3.7K Sep 21 19:09 youphptube.yaml
root@iesus:/var/www/html/YouPHPTube# 
```

**Comment by DanielnetoDotCom** [comment] 2019-10-01 12:11
I think I found the issue, please update and try again.

**Comment by maxlinux2000** [comment] 2019-10-01 17:54
hemmm..... how to update? :)  is there some commands with git to do, or I have to reinstall all system? Sorry for this question so trivial for you

**Comment by DanielnetoDotCom** [comment] 2019-10-01 18:06
here: https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube

**Comment by maxlinux2000** [comment] 2019-10-01 18:52
I just upgrade to 7.7 without errors...
but sorry, something was wrong....

![Captura de pantalla de 2019-10-01 20-47-12](https://user-images.githubusercontent.com/5683921/65991188-34de0d00-e48d-11e9-9089-bcf692bbfa0c.png)

**Comment by DanielnetoDotCom** [comment] 2019-10-01 18:54
where did you click to get it?

can you please clear your browser cache??
can you please inspect your code for Javascript errors?
can you reproduce it on demo site?

**Comment by maxlinux2000** [comment] 2019-10-01 19:27
Please have a look here:

https://iesus.win/video/youphptube-error3

and here

https://iesus.win/video/youphptube-error4

...I need to buy the switch resolution plugin....I know...

**Comment by maxlinux2000** [comment] 2019-10-01 19:38
...and yes... the same occurs in Demos site.

https://iesus.win/video/youphptube-error4-demo

**Comment by DanielnetoDotCom** [comment] 2019-10-01 21:39
Thanks, now I see, please update and try again

**Comment by maxlinux2000** [comment] 2019-10-02 08:25
much better, but not compltetly fixed

I've updated 
![Captura de pantalla de 2019-10-02 09-35-29](https://user-images.githubusercontent.com/5683921/66026210-9be4db80-e4f8-11e9-8029-df697dca4607.png)

Then clear che cache, add an article, but the images still not works.  But this time I have saved the articele and the edited... bingo! It's works!
So the bug is fixed in the edit mode, but not in the creation mode. Have a look in the video

https://iesus.win/video/youphptube-error5

The filter jpg and gif works.

![Captura de pantalla de 2019-10-02 10-22-41](https://user-images.githubusercontent.com/5683921/66028989-9b4f4380-e4fe-11e9-8a7e-a94c15de9a98.png)

Only other question:

It's possible habe the picture a bit more bigger and without the time 00:00:00 ?

**Comment by DanielnetoDotCom** [comment] 2019-10-02 12:53
What do you mean it is not working on creation mode?

the 00:00:00 will be removed

**Comment by maxlinux2000** [comment] 2019-10-04 09:32
Forget it, I can no longer reproduce the error.
When I was about to create the first article (I never believed one in this database) the insertion of the images did not work for me. But now it works perfectly.
It is possible that this small error is verified only when the table of the articles is empty.

**Closed** 2020-04-11 06:15 UTC
Labels: wontfix
