### ISSUE TITLE
Video Thumbnails not showing with YPTStorage Plugin

### ISSUE THREAD

**Issue by JSY-Ben** [WWBN/AVideo#4554] opened 2021-02-13 21:06 UTC
Hi :) Thanks as usual for such great software.

Have just yesterday updated all my code and plugins, and have come up with an unusual problem where on the 'Gallery' plugin, the first page will not show some thumbnails as seen here:

<img width="1864" alt="Screenshot 2021-02-13 at 9 02 25 PM" src="https://user-images.githubusercontent.com/13555701/107861600-cc53be00-6e3e-11eb-9e11-5bb16f2f97e5.png">

The only difference between the videos with the thumbnails not working and the ones that are is that the thumbnails that do work are on the 'Local' Storage, and the ones that don't work are stored elsewhere using the YPTStorage plugin.

This has worked fine up until the recent update.

As a test, i have moved the videos with the broken thumbnails to the 'Local' storage and the thumbnails then work. Once moving them back, they break again.

Oddly enough, if i clear the cache directory, and first page cache, as well as my local computer cache, the thumbnails work for one page refresh, then break again.

This is what is appearing in the log if its useful:

 [13-Feb-2021 20:55:14 Europe/Jersey] PHP Warning:  file_get_contents(/var/www/html/www.mysite.com/streamer/videos/_YPTuniqid_60255a11b45e61.42704367_SD.mp4.size.lock): failed to open stream: No such file or directory in /var/www/html/www.mysite.com/streamer/objects/functions.php on line 1239

#1282 [13-Feb-2021 20:55:14 Europe/Jersey] PHP Warning:  filesize(): stat failed for /var/www/html/www.mysite.com/streamer/videos/_YPTuniqid_60255a11b45e61.42704367_SD.mp4.size.lock in /var/www/html/www.mysite.com/streamer/objects/functions.php on line 1239

 [13-Feb-2021 20:40:30 Europe/Jersey] PHP Warning:  file_put_contents(/var/www/html/www.mysite.com/streamer/videos/cache/YPTWget/ad6c2663e89a82bedfb6e24b7b608f09.lock): failed to open stream: No such file or directory in /var/www/html/www.mysite.com/streamer/objects/functions.php on line 4262

[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php

[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php

[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php

[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php

[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: getVideosURL_V2:: dummy file found, fix cache ["\/^https:\\\/\\\/hightube.highlands.ac.uk\\\/streamer\\\/videos\/","https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4",0,10,{"filename":"_YPTuniqid_602840c5cb1448.97424249_SD.mp4","path":"\/var\/www\/html\/hightube.highlands.ac.uk\/streamer\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","url":"https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","type":"video","format":"mp4"}] SCRIPT_NAME: /streamer/view/index.php
[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: Video:clearCache(6278) SCRIPT_NAME: /streamer/view/index.php
[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: deleteVideoTags getVideoTags6278 SCRIPT_NAME: /streamer/view/index.php
[13-Feb-2021 21:29:02 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/view/index.php

Any ideas would be appreciated.

Many thanks.

**Comment by DanielnetoDotCom** [comment] 2021-02-16 12:30
I could not reproduce it here, I am confused.

are you using the encoder or direct upload?

also, I am interested to see the log after 13-Feb-2021 21:29:02

**Comment by JSY-Ben** [comment] 2021-02-16 19:57
Hi there.

Am using a self-hosted encoder with the correct plugins to make the thumbnails work. All up-to-date. Like i say, if i clear all cache files, and browser cache, the thumbnails work. It even works it seems if i refresh the same page a few times. But if i click on a video to play it, then go back to the homepage, the thumbnails don't work until i clear the cache again. Here is the log below for that period i did this, as well as the errors that appeared on the webpage when the thumbnails didn't work. Many thanks :)

<img width="1920" alt="Screenshot 2021-02-16 at 7 56 24 PM" src="https://user-images.githubusercontent.com/13555701/108114720-1633e280-7091-11eb-8fd6-e92ba3561674.png">

The links in that error of course don't work, however if i clear the cache and try the same links, they DO work. But then another refresh later, they don't :D 



[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: getVideosURL_V2:: dummy file found, fix cache ["\/^https:\\\/\\\/hightube.highlands.ac.uk\\\/streamer\\\/videos\/","https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4",0,10,{"filename":"_YPTuniqid_602840c5cb1448.97424249_SD.mp4","path":"\/var\/www\/html\/hightube.highlands.ac.uk\/streamer\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","url":"https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","type":"video","format":"mp4"}] SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: Video:clearCache(6278) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: deleteVideoTags getVideoTags6278 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:30 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:35 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/objects/configurationClearCache.json.php
[16-Feb-2021 19:47:38 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/objects/configurationClearCache.json.php
[16-Feb-2021 19:47:38 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/objects/configurationClearCache.json.php
[16-Feb-2021 19:47:45 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/_jpg_602c21615e9dc.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:45 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:45 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:45 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:45 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602840c5cb1448.97424249_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:52 Europe/Jersey] AVideoLog::DEBUG: getVideosURL_V2:: dummy file found, fix cache ["\/^https:\\\/\\\/hightube.highlands.ac.uk\\\/streamer\\\/videos\/","https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4",0,10,{"filename":"_YPTuniqid_602840c5cb1448.97424249_SD.mp4","path":"\/var\/www\/html\/hightube.highlands.ac.uk\/streamer\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","url":"https:\/\/hightube.highlands.ac.uk\/streamer\/videos-user\/videos\/_YPTuniqid_602840c5cb1448.97424249_SD.mp4","type":"video","format":"mp4"}] SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:52 Europe/Jersey] AVideoLog::DEBUG: Video:clearCache(6278) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:53 Europe/Jersey] AVideoLog::DEBUG: deleteVideoTags getVideoTags6278 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:47:53 Europe/Jersey] AVideoLog::DEBUG: ObjectYPT::setLastDeleteALLCacheTime /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/lastDeleteALLCacheTime.cache SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:49:15 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/page/230?page=222&) FROM: 10.90.152.1 Browser: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.153 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:50:53 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/objects/comments.json.php?video_id=106) FROM: 10.90.152.1 Browser: Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/88.0.4324.163 Safari/537.36 SCRIPT_NAME: /streamer/objects/comments.json.php
[16-Feb-2021 19:51:04 Europe/Jersey] AVideoLog::DEBUG: User::userCanWatchVideoWithAds (No can not)  6218 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:04 Europe/Jersey] AVideoLog::DEBUG: User::canWatchVideo You are not logged so can not see (6218) session_id=07lma2qdd6vonbm5ms0tstvf0n SCRIPT_NAME=/streamer/view/index.php IP = 157.55.39.79 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:04 Europe/Jersey] AVideoLog::DEBUG: User::canWatchVideo (No can not) 6218 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:18 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/cat/client-work) FROM: 10.90.152.1 Browser: MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:28 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/cat/pitches) FROM: 10.90.152.1 Browser: MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:29 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:29 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:29 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:29 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_602405aca04985.17658499_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:38 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/cat/audio) FROM: 10.90.152.1 Browser: MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:42 Europe/Jersey] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1219 takes 3.9297 seconds to complete, Limit (0.7). /var/www/html/hightube.highlands.ac.uk/streamer/view/index.php SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:42 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:42 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:42 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:42 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5de4da2b5d8262.72441959_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:52 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/cat/comedy) FROM: 10.90.152.1 Browser: MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:51:58 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/cat/films) FROM: 10.90.152.1 Browser: MTRobot/0.2 (Metrics Tools Analytics Crawler; https://metrics-tools.de/robot.html; crawler@metrics-tools.de) SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:00 Europe/Jersey] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1219 takes 0.8555 seconds to complete, Limit (0.7). /var/www/html/hightube.highlands.ac.uk/streamer/view/index.php SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:01 Europe/Jersey] AVideoLog::DEBUG: Warning: Slow process detected [video::getAllVideos foreach] On  Line 1219 takes 1.1638 seconds to complete, Limit (0.7). /var/www/html/hightube.highlands.ac.uk/streamer/view/index.php SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:01 Europe/Jersey] AVideoLog::DEBUG: Resize JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339_thumbsV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:01 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339_thumbsV2.jpg, 250, 140, 80 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:01 Europe/Jersey] AVideoLog::DEBUG: Resize Small JPG /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339_thumbsSmallV2.jpg SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:01 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339.jpg, /var/www/html/hightube.highlands.ac.uk/streamer/videos/_YPTuniqid_5ebc4ace9fb090.82226339_thumbsSmallV2.jpg, 250, 140, 5 SCRIPT_NAME: /streamer/view/index.php
[16-Feb-2021 19:52:04 UTC] AVideoLog::DEBUG: Bot Detected, NOT showing the cache (/streamer/channel/5ba89b19aace8?current=) FROM: 10.90.152.1 Browser: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html) SCRIPT_NAME: /streamer/view/channel.php
[16-Feb-2021 19:52:04 Europe/Jersey] PHP Notice:  getimagesize(): Read error! in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php on line 2925
[16-Feb-2021 19:52:04 Europe/Jersey] PHP Notice:  Trying to access array offset on value of type bool in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php on line 2926
[16-Feb-2021 19:52:04 Europe/Jersey] PHP Notice:  exif_imagetype(): Read error! in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php on line 1639
[16-Feb-2021 19:52:04 Europe/Jersey] PHP Warning:  imagecreatefrompng(): '/var/www/html/hightube.highlands.ac.uk/streamer//videos/userPhoto/photo76.png' is not a valid PNG file in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php on line 1649
[16-Feb-2021 19:52:04 Europe/Jersey] AVideoLog::DEBUG: convertImage: could not create a resource /var/www/html/hightube.highlands.ac.uk/streamer//videos/userPhoto/photo76.png, /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/_jpg_602c226439aa8.jpg, 100 SCRIPT_NAME: /streamer/view/channel.php
[16-Feb-2021 19:52:04 Europe/Jersey] AVideoLog::DEBUG: im_resizeV2: /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/_jpg_602c226439aa8.jpg, /var/www/html/hightube.highlands.ac.uk/streamer//videos/userPhoto/photo76_og_200X200.jpg, 200, 200, 100 SCRIPT_NAME: /streamer/view/channel.php
[16-Feb-2021 19:52:04 Europe/Jersey] AVideoLog::DEBUG: im_resize: Source not found: /var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/_jpg_602c226439aa8.jpg SCRIPT_NAME: /streamer/view/channel.php
[16-Feb-2021 19:52:04 Europe/Jersey] PHP Warning:  unlink(/var/www/html/hightube.highlands.ac.uk/streamer/videos/cache/_jpg_602c226439aa8.jpg): No such file or directory in /var/www/html/hightube.highlands.ac.uk/streamer/objects/functions.php on line 2931
[16-Feb-2021 19:52:06 Europe/Jersey] AVideoLog::DEBUG: Warning: Slow process detected [/var/www/html/hightube.highlands.ac.uk/streamer/view/channelBody.php - channelName: 5ba89b19aace8] On  Line 203 takes 1.6015 seconds to complete, Limit (0.7). /var/www/html/hightube.highlands.ac.uk/streamer/view/channel.php SCRIPT_NAME: /streamer/view/channel.php

**Comment by guymass** [comment] 2021-02-16 21:57
I have the same issue although I haven't considered it has anything to do with YPTStorage plugin because I moved server recently and moved many videos around and while at time they were transferred wrongly due to bad config. So I wanted to ask if there is a way to regenerate those thumbs if they are missing? and also the jpeg on the video list page under my videos, I have many missing thumbnails which I don't know how to regenerate them without reuploading the video and loosing all the viewers count.

![Screen Shot 5781-06-04 at 23 51 32](https://user-images.githubusercontent.com/58882903/108126547-a33b6380-70b2-11eb-9fd7-88906d505804.jpg)

**Comment by DanielnetoDotCom** [comment] 2021-02-18 10:59
The plugin MP4ThumbsAndGif can generate the thumbs one by one, we do not have a bulk script yet

**Closed** 2021-03-23 18:17 UTC
Labels: bug, wontfix
