### ISSUE TITLE
Disk quota exceeded when no videos are owned

### ISSUE THREAD

**Issue by barrunning** [WWBN/AVideo#6233] opened 2022-02-01 12:08 UTC
Assigned a member a disk quota of 250mb. They have not uploaded a single video. When member goes to play a video larger than disk quota a denied message pops up saying disk quota exceeded.

**Comment by DanielnetoDotCom** [comment] 2022-02-01 16:10
I am not 100% what do you mean but if this message pops up the video owner may exceed his quota.

please share your DiskQuota plugin parameters screenshot

**Comment by barrunning** [comment] 2022-02-01 16:44
![2A5C3D6B-ABC2-4E66-A787-21034A2BC96E](https://user-images.githubusercontent.com/58601786/152011726-c879f8a8-a518-4d33-b995-c8aa7491f3c5.jpeg)

**Comment by barrunning** [comment] 2022-02-01 16:45
When a person with a low quota . Say 250mb tries to watch a video. The message pops up disk quota exceeded. They have not uploaded a single video.

**Comment by barrunning** [comment] 2022-02-01 16:55
![6EB1C07F-3990-4EC6-9E20-AD3EE7BB8C7B](https://user-images.githubusercontent.com/58601786/152013724-aeaefe93-9050-43d7-954b-b0eb3680df04.png)
![246087E8-D7EE-4581-B6FF-9CCD7E813C0E](https://user-images.githubusercontent.com/58601786/152013745-91e98b64-bf8c-4504-9e0e-919d3c8512fe.png)

**Comment by barrunning** [comment] 2022-02-01 16:56
The above is with disk quota enabled.
The following is without disk quota.
![E384C123-E009-46EB-9641-1472CADD94D2](https://user-images.githubusercontent.com/58601786/152013971-a7e29c68-dc2e-410d-9785-25421572fe9c.png)

**Comment by DanielnetoDotCom** [comment] 2022-02-01 17:59
> When a person with a low quota . Say 250mb tries to watch a video. The message pops up disk quota exceeded. They have not uploaded a single video.

the problem is not the quota from who is watching, the problem is the quota from the video owner

**Comment by DanielnetoDotCom** [comment] 2022-02-01 18:00
I guess you are mixing things. looks like you have a PPV os subscription enabled too.

you must define your business model first. 

is very dangerous to just enable the plugins.

**Comment by barrunning** [comment] 2022-02-01 18:53
So you can’t have a business model with videos available for Ppv outside of the subscription then also charge for those that want to upload a video to be reviewed?

**Comment by DanielnetoDotCom** [comment] 2022-02-01 19:07
So you want to charge for storage of the videos, and also have a PPV plan so your paid users can use your PPV and make some money?

I can say it may be possible but this is not that simple. 

you should start doing one thing at a time. 

1. first make sure you have the DiskUploadQuota working properly (disable PPV and Subscription)
2. once it is working properly enable the PPV and create some plans  
3. Do the same on the subscription

## Payment

The main problem is who will receive the payment
the thing is, the way it is now all the money goes to you. 

### your users will receive a payment directly

I am not 100% but I guess the PPV your users can enter their PapPay API keys, 

the good thing about this is that you do not have to deal with the payment gateway fees

but this is not a simple task, your users may know what they are doing, helping your users to set up their account may give you some headache

### you will receive the payment and you will pay them

the other option is to enable the wallet and you will pay your users

so all the money goes to you, with PayPal you can enable the automatic withdraw, so your users can request to withdraw the money from their wallets

on that case you will have to deal with the PayPal fees, so would be good for you to get a cut from each PPV

**Comment by barrunning** [comment] 2022-02-01 20:37
No no. 
i am the only one charging.
So I have videos that are available as Ppv. I also have a subscription plan where they can access more services.
One of those plans is they can upload a video for me to see. I don’t want them uploading huge files.  Hence disk quota.

**Comment by DanielnetoDotCom** [comment] 2022-02-02 11:05
this should work

so again, the quota exceeds alert comes from the video owner, NOT from the viewer.

About the video you are trying to watch, who is the video owner?
Does that owner has a disk quota available?

**Comment by barrunning** [comment] 2022-02-02 13:01
I am the video owner. I have the maximum amount of disk space. Not even close to reaching quota.

**Comment by DanielnetoDotCom** [comment] 2022-02-02 13:13
Ok, can you please email me both users and passwords, so I will take a direct look into your configuration?

also email me the video link that you are using for test.

**Comment by barrunning** [comment] 2022-02-02 13:25
Email sent. Subject disk quota

**Comment by DanielnetoDotCom** [comment] 2022-02-02 14:07
Tested on movementa....com

It is clear to me the video owner has no DiskQuota

![image](https://user-images.githubusercontent.com/18009293/152162844-8060ef49-5253-448a-8cf5-a0e390a2ee1a.png)

I found a problem deleting a plan, and it is fixed now.

and I took the opportunity to change the plugin, and now admins do not exceed quota anymore and your "business plan" should work now

**Closed** 2022-02-03 19:41 UTC
Labels: bug
