### ISSUE TITLE
VM CPU load 100% after latest update

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#3525] opened 2020-08-16 10:38 UTC
Hey

I don't know what happened, but after latest update (9.4) my cpu load went 100%. No special network traffic happening.. 
 Can you help please?

![image](https://user-images.githubusercontent.com/63721378/90332429-aeeb8780-dfb4-11ea-9b56-69cd987a72f4.png)

**Comment by akhilleusuggo** [comment] 2020-08-16 10:39
provide some logs , or JavaScript errors 
https://github.com/WWBN/AVideo/wiki/How-to-find-errors-on-AVideo-Platform
https://github.com/WWBN/AVideo/wiki/Using-Your-Browser-Console-to-Diagnose-JavaScript-Errors

Without detail hard to know what's wrong

**Comment by tonuzo** [comment] 2020-08-16 10:49
Nothing special on java console. 
This is basically what avideo.log says repeatedly:

![image](https://user-images.githubusercontent.com/63721378/90332624-5b7a3900-dfb6-11ea-97fe-f07221b6f2ad.png)

**Comment by akhilleusuggo** [comment] 2020-08-16 10:51
I think that's the issue . Is not repeatedly , but spamming I guess . All those logs made at the same second as I can see .

**Comment by tonuzo** [comment] 2020-08-16 10:53
What can I do, and why did it start after update?

**Comment by akhilleusuggo** [comment] 2020-08-16 10:54
Anyway if you think the issue is from mysql , than check the logs: 
Mysql . Location : `/var/log/mysql/error.log`
Apache2 . Location : /var/log/apache2/error.log

**Comment by tonuzo** [comment] 2020-08-16 11:11
Apache2 log:

There's alot "connection refuesed" line

![image](https://user-images.githubusercontent.com/63721378/90332958-4d79e780-dfb9-11ea-9661-9ff705e2f0c9.png)

**Comment by tonuzo** [comment] 2020-08-16 11:19
I noticed when I load the site, CPU is fine, but when I load a category CPU hits the roof... Then I restart Apache and CPU is again back to normal.

**Comment by tonuzo** [comment] 2020-08-16 11:32
Ok. The problem might be in my own custom look plugin. I'm gonna fix that first...

**Comment by akhilleusuggo** [comment] 2020-08-16 11:56
You're not the only one who's suffering from heavy loading issues

**Comment by syldri** [comment] 2020-08-16 12:07
I saw this loading issue today I did a test with 3 different pc when I refresh the page I am 3.6% of the cup

**Comment by TLCReuver** [comment] 2020-08-17 05:50
Same problem here... VM CPU load 50-90% after latest update.
After restarting VM CPU is normal.

**Comment by TLCReuver** [comment] 2020-08-17 05:50
Same problem here... VM CPU load 50-90% after latest update.
After restarting VM CPU is normal.

**Comment by DanielnetoDotCom** [comment] 2020-08-17 11:11
Sorry, still the CPU overload on the streamers?
anything on the logs?

**Comment by DanielnetoDotCom** [comment] 2020-08-17 11:13
try to disable some plugins and identify if is one of them that is consuming the CPU

**Comment by akhilleusuggo** [comment] 2020-08-17 11:14
In my case was the YPT-Storage consuming a lot of RAM for some reason

**Comment by DanielnetoDotCom** [comment] 2020-08-17 11:31
Ok, the Storage we already have an idea what it may be, and it is probably only when it is transferring, and it will be reviewed.

I am concern now about the streamer.

**Closed** 2020-09-19 13:03 UTC
Labels: bug, wontfix
