### ISSUE TITLE
Categories not visible to the public

### ISSUE THREAD

**Issue by JeanDavis91** [WWBN/AVideo#7920] opened 2023-04-18 00:23 UTC
Good morning
I don't understand why the categories for the public are no longer displayed despite the Suggested activation as you explained

Please explain to me why this problem on v12.4

jfr

**Comment by GreenDragonTavern** [comment] 2023-04-18 01:02
To add to Categories dilemma...Don't have a single video in the ***Default*** category yet below is menu, top bar category list, and when I click on ***Default*** there's nothing to show as it should since not a single video is assigned to ***Default***.

![Categories1](https://user-images.githubusercontent.com/85363361/232641783-28b15e5a-6f29-4483-b4a2-a81ce15cefef.jpg)

![Categories2](https://user-images.githubusercontent.com/85363361/232641807-b3041b68-813a-40b8-b1a2-49ab67c7ca87.jpg)

![Categories3](https://user-images.githubusercontent.com/85363361/232641838-d5e2e990-5741-42aa-9284-2cd880f77fdf.jpg)

**Comment by GreenDragonTavern** [comment] 2023-04-18 13:41
Status? There are no videos with a categories_id = 1 in database.

**Comment by JeanDavis91** [comment] 2023-04-19 19:55
Good morning
Categories are no longer displayed on the home page since the update to v12.4
Thank you for your answers

Here with the correct version v 12.3
![bon](https://user-images.githubusercontent.com/61474191/233184563-9d671631-103e-4f82-86a0-0bb3b3e78890.jpg)

Here with version v 12.4 more categories on index
![pas ok](https://user-images.githubusercontent.com/61474191/233184849-ac214bd7-9c04-41a4-9195-35af671f90ef.jpg)
![02](https://user-images.githubusercontent.com/61474191/233184909-04303f73-18d2-4506-962b-041e4f75bf23.jpg)
![03](https://user-images.githubusercontent.com/61474191/233184935-99a13b0f-65ae-4922-9cc7-9322b34eea3c.jpg)
![4](https://user-images.githubusercontent.com/61474191/233184947-f8228405-1327-4c1e-8a54-3d14c934575d.jpg)

I get this error when I quit my avideo
![hs](https://user-images.githubusercontent.com/61474191/233185504-a8d2ef10-b127-43d5-8754-81539b2ddce2.jpg)

**Comment by DanielnetoDotCom** [comment] 2023-04-20 13:59
can you please check the last update regarding categories?

regarding the 502 error I cannot reproduce it

**Comment by GreenDragonTavern** [comment] 2023-04-20 14:47
@DanielnetoDotCom - categoriesTopButtons no longer works when enabled. Just did a git pull...

**Comment by DanielnetoDotCom** [comment] 2023-04-20 14:53
I think I find the issue, please check this update

**Comment by GreenDragonTavern** [comment] 2023-04-20 14:56
That did it, thank you!

**Comment by JeanDavis91** [comment] 2023-04-21 20:17
Hello this did not change anything for the categories on the index page

On this site it works
https://pnt-jfr.synology.me/films-video-12-3/

On this site it still does not work for categories
https://pnt-jfr.synology.me/films-video-12-4/

And for error 502 on version v11.5 I did not have this error

thank you for your work

**Comment by DanielnetoDotCom** [comment] 2023-04-24 11:15
your sites does not work for me

![image](https://user-images.githubusercontent.com/18009293/233980924-d9a19f58-3e83-4d62-8b26-5c2aa69990f7.png)

**Comment by JeanDavis91** [comment] 2023-04-24 11:50
Good evening

The site operates from 2 p.m. to 6 a.m.

THANKS

**Comment by JeanDavis91** [comment] 2023-05-17 01:12
Good morning

I noticed that you have corrected all my problems I thank you for it however when I leave my site I always have this logoff error on version 12.4 on the other hand on version 11.5 I do not have this error

Thank you for your great work

**Comment by DanielnetoDotCom** [comment] 2023-05-29 12:15
duplicated https://github.com/WWBN/AVideo/issues/8066

**Closed by DanielnetoDotCom** 2023-05-29 12:15 UTC
Labels: bug
