### ISSUE TITLE
PPV bug

### ISSUE THREAD

**Issue by tonuzo** [WWBN/AVideo#5217] opened 2021-05-26 08:23 UTC
Hi,

There is a bug in PPV-plugin.  

This might be a bit complicated to explain but I try:

If you make a video serie and add it to PPV usergroup plan, **but not** add individual episodes (of the serie) to "normal" PPV plan, a logged-in user can't buy the serie.  If a user clicks the serie it redirects to this page:

![image](https://user-images.githubusercontent.com/63721378/119624311-af516280-be11-11eb-9090-6d768e6a1a86.png)

Also even if you have activated "Only paid users can see" on an individual episode of the serie. The video is freely viewable with log entry below.

![image](https://user-images.githubusercontent.com/63721378/119625775-3ce18200-be13-11eb-8fa7-376038b7d774.png)

` [25-May-2021 20:52:14] AVideoLog::DEBUG: userCanWatchVideoWithAds the plugin (PayPerView) said user (2) can watch SCRIPT_NAME: /view/index.php` 

Allow free play with ads isn't active in PPV-plugin.
![image](https://user-images.githubusercontent.com/63721378/119627127-926a5e80-be14-11eb-93ad-2247d8027612.png)

So you should have a possibility only sell series without making the episodes as PPV individually.

**Comment by DanielnetoDotCom** [comment] 2021-05-26 12:27
Are you using the PPV plan as a usergroups?

again, use usergroups on the PPV plan and add the videos from this playlist on the same usergroup

**Comment by tonuzo** [comment] 2021-05-27 06:27
Yes I'm using PPV plan as usergroups. But again, it doesn't work right if you **haven't** added the individual videos of the usergroup as a single PPV videos. 

You can test: 

1. add (e.g.) 3 videos to same user group and make it a PPV plan.
2. Don't add the individual videos of that user group to single PPV plan (PPV videos). 
3. Sign in as a user (not admin) that doesn't have that usergroup activated. And the user must not have any plan activated either.
4. Try to click the serie on front page.

Thanks.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 12:07
Hi, to test I still need more details to reproduce what you are doing...

Let's say we have 3 videos: (VIdeo A), (Video B), and (Video C)

We will add all of those videos on a serie (S1), which means S1 will play videos A, B, and C

and we have 1 usergroup: (UG1)

1. add (e.g.) 3 videos to same user group and make it a PPV plan.
2. Don't add the individual videos of that user group to single PPV plan (PPV videos).

 _-- you cannot add an individual video on a PPV with usergroup_

3. Sign in as a user (not admin) that doesn't have that usergroup activated. And the user must not have any plan activated either.
4. Try to click the serie on front page.

_-- so should I add on the usergroup the serie or the video itself?_

**Comment by tonuzo** [comment] 2021-05-27 12:26
> Hi, to test I still need more details to reproduce what you are doing...
> 
> Let's say we have 3 videos: (VIdeo A), (Video B), and (Video C)
> 
> We will add all of those videos on a serie (S1), which means S1 will play videos A, B, and C
> 
> and we have 1 usergroup: (UG1)

Yes, and then you make it a PPV plan. 

And not add Video A, Video B, and Video C individually to plan here:

![image](https://user-images.githubusercontent.com/63721378/119825193-5f50c980-beff-11eb-93e7-beb3c8a4ef50.png)

So now you should be able to reproduce. Remember you have to be logged-in as a non admin.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 12:31
But did you create a plan for UG1?

what is related to UG1?

is S1 on UG1?

are Videos A, B, and C on UG1?

**Comment by tonuzo** [comment] 2021-05-27 12:38
Yes I did a plan for UG1 

S1 is in UG1 

It works if I manually add the UG1 for a user.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 12:43
I see, you MUST add Videos A, B and C on UG1.

let me explain why.

in many cases, you may want to have an introduction or a trailer as the first video on a playlist (Video A). the trailer is free, but the other videos are on a PPV plan (Videos B and C).

so, remove the playlist from UG and add the videos A, B and C

**Comment by tonuzo** [comment] 2021-05-27 13:08
Of course, but videos are in UG1 and you can't buy them because of "video is no available" -page.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 13:16
can you please remove the playlist from UG1?

if you want email me your site credentials and I will look directly at it.

**Comment by tonuzo** [comment] 2021-05-27 13:32
Ok, sent.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 16:11
Hi, 

I checked it on your side and I could confirm it.

I tried to reproduce it on my side but it works fine.

the only way for me to find out is if I can access your server directly and make sure you are up to date

**Comment by tonuzo** [comment] 2021-05-27 16:32
Well that's odd, everything is up to date..

**Comment by DanielnetoDotCom** [comment] 2021-05-27 16:47
I got something ....

please turn this playlist "Voimaannuttava synty" into a series

![image](https://user-images.githubusercontent.com/18009293/119865439-09295980-bef2-11eb-9b0a-ac5a0803decc.png)

**Comment by DanielnetoDotCom** [comment] 2021-05-27 16:52
Also if you can give me the playlist owner credentials, so I can check it.

**Comment by tonuzo** [comment] 2021-05-27 17:11
It is a serie already. Admin is the owner of the playlist, but not owner of the videos.

**Comment by DanielnetoDotCom** [comment] 2021-05-27 17:15
what is the series video name/id?

**Comment by tonuzo** [comment] 2021-05-27 17:21
playlists_id=12027

**Comment by DanielnetoDotCom** [comment] 2021-05-27 17:31
what is the series title? and videos_id?

**Comment by DanielnetoDotCom** [comment] 2021-05-27 17:32
can I reset this user password so I can test it?

**Comment by tonuzo** [comment] 2021-05-27 17:33
yes sure

**Comment by DanielnetoDotCom** [comment] 2021-05-27 17:40
who is the playlist owner? I cannot check without access to the server

**Comment by DanielnetoDotCom** [comment] 2021-05-27 19:10
I am trying hard and I cannot find the reason.

we now have 2 options, or you give me access to the server or you reproduce it on the demo site.

**Comment by tonuzo** [comment] 2021-05-27 19:51
Check your mail

**Comment by DanielnetoDotCom** [comment] 2021-05-27 21:20
Hi, thanks I found the bug, and your site is updated.

this bug is fixed on PayPerView V4.5

**Comment by tonuzo** [comment] 2021-05-28 06:25
Thanks for the investigation and finding the bug. 

But I'm sorry to tell that it doesn't quite work yet. 

Now you can purchase but after purchase it doesn't work. 

- Now it redirects a user to first video of that serie, but not to the playlist.
- If you try to click the purchased playlist the "video not found" error page shows 
- On top left corner there is a string: 
![image](https://user-images.githubusercontent.com/63721378/119939157-126c0200-bf96-11eb-9a49-6ece3478892c.png)
- On the main page if you click the serie you can see there is the "expires" time something not right. It shoud be only 30 days.
![image](https://user-images.githubusercontent.com/63721378/119939339-5eb74200-bf96-11eb-98c6-03f0bbee3ffa.png)

**Comment by DanielnetoDotCom** [comment] 2021-05-28 13:32
> Now it redirects a user to first video of that serie, but not to the playlist.

Fixed version 4.6

> If you try to click the purchased playlist the "video not found" error page shows

can you please give me an account so I can try?

> On top left corner there is a string:

Fixed, was a missing debug code in your installation only

> On the main page if you click the serie you can see there is the "expires" time something not right. It shoud be only 30 days.

what account and what page can I check that?

**Comment by DanielnetoDotCom** [comment] 2021-05-28 19:08
Hi, 

I guess I found all bugs ver 4.7, please check

**Comment by tonuzo** [comment] 2021-05-28 20:26
It's working! Great job! I think this was a tricky one :) 

Only one minor thing left, in the final "pay now" page these aren't translatable:   

![image](https://user-images.githubusercontent.com/63721378/120037731-c1e2bc00-c00a-11eb-9be5-5817217d7d9d.png)

But anyway thank you for your good work to fixing this.

**Comment by DanielnetoDotCom** [comment] 2021-05-31 12:33
Regarding the translation, I guess your language does not have the "Pay Now" translation

what language are you using?

**Closed** 2021-07-04 03:42 UTC
Labels: bug, wontfix
