### ISSUE TITLE
Healtgcheck issue on website

### ISSUE THREAD

**Issue by kollossus55** [WWBN/AVideo#8879] opened 2024-03-09 16:40 UTC
hi 
doing a healthcheck on website and I came across this error in attachment.
Looking at logfiles I see the following:-
============================================
[09-Mar-2024 16:29:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:29:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:29:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 08:28:44 America/Los_Angeles] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 08:28:44 America/Los_Angeles] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:26:09 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:26:09 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:25:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:25:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:25:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:21:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:21:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:21:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:19:13 Europe/London] AVideoLog::DEBUG: postVariables: https://search.ypt.me/checkPorts.json.php [6] - Could not resolve host: search.ypt.me SCRIPT_NAME: /admin/index.php
 [09-Mar-2024 16:19:13 Europe/London] AVideoLog::DEBUG: Verification Response (https://search.ypt.me/verify.php?url=https%3A%2F%2Fwww.mysite.com%2F&screenshot=1):  SCRIPT_NAME: /admin/index.php
 [09-Mar-2024 16:19:13 Europe/London] AVideoLog::DEBUG: Verification GetFrom Cache /tmp/e7885683a643d20fcb05f43a8d10c59e_verify.log SCRIPT_NAME: /admin/index.php
 [09-Mar-2024 16:19:13 Europe/London] AVideoLog::DEBUG: Verification Start https://www.mysite.com/ cacheFile=/tmp/e7885683a643d20fcb05f43a8d10c59e_verify.log SCRIPT_NAME: /admin/index.php
 [09-Mar-2024 16:18:49 Europe/London] AVideoLog::DEBUG: login.json.php user found SCRIPT_NAME: /objects/login.json.php
 [09-Mar-2024 16:18:49 UTC] AVideoLog::DEBUG: User:login finish with success users_id=1 SCRIPT_NAME: /objects/login.json.php
 [09-Mar-2024 16:18:44 Europe/London] AVideoLog::DEBUG: getCaptchaImage: j5l8J - session_name 84b11d010cced71edffee7aa62c4eda0 session_id: 4vcn5dpdgh12dj57vhr6t0jog6 SCRIPT_NAME: /objects/getCaptcha.php
 [09-Mar-2024 16:18:42 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:18:42 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:18:30 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:18:30 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:17:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 16:17:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 16:16:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:16:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:16:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 18:15:56 Africa/Cairo] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 18:15:56 Africa/Cairo] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:13:24 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:13:24 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 18:13:15 Africa/Cairo] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 18:13:15 Africa/Cairo] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:12:18 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:12:18 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:11:16 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:11:16 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:11:15 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:10:47 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:10:47 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:06:08 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:06:08 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:06:08 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:04:42 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:04:42 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 16:01:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:01:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 16:01:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:59:02 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:59:02 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:58:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:58:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:57:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:57:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:57:11 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:55:28 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:55:28 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:53:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:53:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:53:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:49:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:49:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:49:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:46:02 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:46:02 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:45:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:45:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:45:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:41:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:41:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:41:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:39:26 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:39:26 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:37:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:37:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:37:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:35:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:35:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:33:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:33:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:33:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:29:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:29:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:29:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:25:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:25:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:25:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 18:23:26 Europe/Moscow] AVideoLog::DEBUG: getCaptchaImage: zm2QF - session_name 84b11d010cced71edffee7aa62c4eda0 session_id: nf4uh5b0ut3mmm6gmcgvv7b5vt SCRIPT_NAME: /objects/getCaptcha.php
 [09-Mar-2024 15:21:06 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:21:06 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:21:06 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 18:20:56 Europe/Moscow] AVideoLog::DEBUG: getCaptchaImage: ZSy2A - session_name 84b11d010cced71edffee7aa62c4eda0 session_id: nf4uh5b0ut3mmm6gmcgvv7b5vt SCRIPT_NAME: /objects/getCaptcha.php
 [09-Mar-2024 15:17:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:17:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:17:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:17:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:17:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:16:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:16:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:15:40 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:15:40 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:13:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:13:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:13:10 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 18:12:54 Europe/Moscow] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 18:12:54 Europe/Moscow] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:09:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:09:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:09:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:07:10 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:07:10 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 15:06:48 Europe/London] AVideoLog::DEBUG: getCurrentPage current>100 ERROR bot die [116] https://www.www.mysite.com/view/trending.php?current=116 Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot) SCRIPT_NAME: /view/trending.php
 [09-Mar-2024 15:06:02 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:06:02 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:05:32 Europe/London] AVideoLog::DEBUG: getCurrentPage current>100 ERROR bot die [124] https://www.www.mysite.com/view/trending.php?current=124 Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot) SCRIPT_NAME: /view/trending.php
 [09-Mar-2024 15:05:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:05:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:05:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:04:22 Europe/London] AVideoLog::DEBUG: getCurrentPage current>100 ERROR bot die [127] https://www.www.mysite.com/view/trending.php?current=127 Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot) SCRIPT_NAME: /view/trending.php
 [09-Mar-2024 15:03:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:03:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 15:00:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:00:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 15:00:14 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 17:57:35 Europe/Moscow] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 17:57:35 Europe/Moscow] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 14:56:12 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:56:12 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:56:12 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:56:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 14:56:01 Europe/London] AVideoLog::DEBUG: setLastVisit error on create file path/to/my/streamer/site/videos/cache/schedulerLastVisit.log SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
 [09-Mar-2024 14:55:01 Europe/London] AVideoLog::DEBUG: Live::isKeyLiveInStats key is empty SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 14:55:01 Europe/London] AVideoLog::DEBUG: isLiveAndIsReadyFromKey::key:  checking SCRIPT_NAME: /plugin/Live/latestOrLive.php
 [09-Mar-2024 14:52:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: page SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:52:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: install SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:52:09 Europe/London] AVideoLog::DEBUG: Plugin Not Found 2: Objects SCRIPT_NAME: /view/info.php
 [09-Mar-2024 14:51:01 Europe/London] AVideoLog::DEBUG: ERROR: Last visit NOT set {"file":"\/var\/www\/html\/AVideo\/videos\/cache\/schedulerLastVisit.log","size":0} SCRIPT_NAME: path/to/my/streamer/site/plugin/Scheduler/run.php
=======================================================================
what do I need to do ?

Regards 

![Health check error](https://github.com/WWBN/AVideo/assets/53856825/51016e56-180d-429f-980a-b88e21088aab)

**Comment by DanielnetoDotCom** [comment] 2024-03-09 20:03
the problem is this

`Could not resolve host: search.ypt.me `

you may want to `ping search.ypt.me` from your server and resolve why it is not resolving the host

**Comment by kollossus55** [comment] 2024-03-10 15:44
Can you investigate ? An hours support..
________________________________

**Comment by kollossus55** [comment] 2024-03-11 09:40
Doing support shortly..

**Closed** 2024-03-11 12:20 UTC
